### ISSUE TITLE
will this work for blob trigger and i want to deploy on kubernetes with keda 

### ISSUE THREAD

**Issue by jainshikha** [Azure-Samples/hello-spring-function-azure#19]
will this work for blob trigger and i want to deploy on kubernetes with keda 
is dockerization possible for this ?

**Comment by jdubois** [comment]
You mean something like this: https://github.com/kedacore/sample-hello-world-azure-functions ? Unless I'm missing something (a specific tool or Maven plugin to help), I believe there would be a significant amount of work to do this. At least, that's not something I've tried or that I have even heard of.

**Comment by jainshikha** [comment]
yes some thing like this but triggers on Blob. i have done with python but wanted to try with java.
facing issue with connection string setting.
i guess  i am doing something wrong.
when setting in local.setting.json it works but while reading from env variable its not able to start.
if you have any idea about it can you share?

and regarding the jar name. can we change the name of jar for gradlew azureFunctionsPackage/azureFunctionsRun ??

**Comment by jdubois** [comment]
For environment variables, it's hard to help you with this little information. You can have a try at reading them in Java and showing them in the log, to be sure that they are correctly set up.
For the Jar name, shouldn't it be fixed? I remember that for App Service it needs to be called "app.jar". I'm not sure here, but as Azure Functions are built on top of the same technology that is a possibility. Otherwise, I guess you can call it the way you want.
