### ISSUE TITLE
Use FunctionInvoker instead of AzureSpringBootRequestHandler in the sample

### ISSUE THREAD

**Issue by konjp** [Azure-Samples/hello-spring-function-azure#29]
`org.springframework.cloud.function.adapter.azure.AzureSpringBootRequestHandler` is deprecated in favor of `org.springframework.cloud.function.adapter.azure.FunctionInvoker`.

**Comment by jdubois** [comment]
Indeed, the API has evolved, but in my experience that new API is a bit buggy (I have NPE when executing my function as it's not correctly registered in the functions catalog, and also Spring Webflux doesn't seem well supported). This is very new, and it's not yet in the official documentation, so I suggest we wait a bit until we migrate to it.
If you have another experience, and have a working example, I'm happy to discuss this with you.
One of the good news is that Oleg told me he took some of my code and put it inside Spring Functions, so that should simplify some code here.

**Comment by konjp** [comment]
Maybe you can check this [issue](https://github.com/spring-cloud/spring-cloud-function/issues/692), and when 3.1.3 is released, probably then you can update sample.

**Comment by jdubois** [comment]
Oh you're good @konjp - that's exactly the core of my issue!!! Oleg says it will be released tomorrow, so let's wait a bit, and let's do this.

**Comment by jdubois** [comment]
This is fixed, thanks a lot @konjp !
